/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany;

import java.awt.BorderLayout;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabo
 */
public class tipoAsistenciaPanel extends javax.swing.JPanel {

    /**
     * Creates new form tipoAsistenciaPanel
     */
    public tipoAsistenciaPanel() {
        initComponents();
          comboPeriodoIndividual.setModel(new DefaultComboBoxModel<>(
        new String[]{"Último mes", "Último trimestre", "Último semestre"}));
    
    comboPeriodoGeneral.setModel(new DefaultComboBoxModel<>(
        new String[]{"Último mes", "Último trimestre", "Último semestre"}));
    
        cargarEmpleadosEnComboBox();
    }
    
      private void cargarEmpleadosEnComboBox() {
        comboEmpleados.removeAllItems();
        comboEmpleados.addItem("Selecciona un empleado");

        String query = "SELECT NOMBRE_COMPLETO FROM empleados";
        try (Connection con = ConexionBD.obtenerConexion(); 
             Statement stmt = con.createStatement(); 
             ResultSet rs = stmt.executeQuery(query)) {
            while (rs.next()) {
                String nombreEmpleado = rs.getString("NOMBRE_COMPLETO");
                comboEmpleados.addItem(nombreEmpleado);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar empleados: " + e.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        comboPeriodoGeneral = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        comboEmpleados = new javax.swing.JComboBox<>();
        comboPeriodoIndividual = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setToolTipText("Individual");

        comboPeriodoGeneral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ultimo mes", "Ultimo trimestre", "Ultimo semestre" }));

        jButton2.setText("Generar reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(comboPeriodoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(comboPeriodoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        comboPeriodoIndividual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ultimo mes", "Ultimo trimestre", "Ultimo semestre" }));

        jButton1.setText("Generar reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecciona un empleado");

        jLabel2.setText("Selecciona un periodo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(comboPeriodoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(comboPeriodoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Individual", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          if (comboEmpleados.getSelectedIndex() <= 0) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un empleado", 
            "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String periodo = (String) comboPeriodoIndividual.getSelectedItem();
    int meses = obtenerMesesDePeriodo(periodo);
    String nombreEmpleado = (String) comboEmpleados.getSelectedItem();
    
    try (Connection con = ConexionBD.obtenerConexion()) {
        // Obtener ID del empleado
        int idEmpleado = obtenerIdEmpleado(con, nombreEmpleado);
        
        // Consultar asistencias
        String sql = "SELECT a.FECHA, a.ESTADO, a.HORA_ENTRADA, a.HORA_SALIDA, a.OBSERVACIONES " +
                     "FROM asistencias a " +
                     "WHERE a.ID_EMPLEADO = ? AND a.FECHA BETWEEN DATE('now', ?) AND DATE('now') " +
                     "ORDER BY a.FECHA DESC";
        
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setInt(1, idEmpleado);
        stmt.setString(2, "-" + meses + " months");
        
        ResultSet rs = stmt.executeQuery();
        
        // Mostrar resultados en una tabla
        mostrarResultadosEnTabla(rs, "Asistencias de " + nombreEmpleado + " - " + periodo);
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error en la consulta: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private int obtenerMesesDePeriodo(String periodo) {
    switch (periodo) {
        case "Último trimestre": return 3;
        case "Último semestre": return 6;
        default: return 1; // Último mes por defecto
    }
}

private void mostrarResultadosEnTabla(ResultSet rs, String titulo) throws SQLException {
    // Crear JDialog en lugar de JFrame
    JDialog dialog = new JDialog((JFrame)null, titulo, true); // Modal
    dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    
    // Crear modelo de tabla
    DefaultTableModel model = new DefaultTableModel();
    
    // Agregar columnas
    ResultSetMetaData metaData = rs.getMetaData();
    for (int i = 1; i <= metaData.getColumnCount(); i++) {
        model.addColumn(metaData.getColumnName(i));
    }
    
    // Agregar filas
    while (rs.next()) {
        Object[] row = new Object[metaData.getColumnCount()];
        for (int i = 1; i <= metaData.getColumnCount(); i++) {
            row[i - 1] = rs.getObject(i);
        }
        model.addRow(row);
    }
    
    JTable tabla = new JTable(model);
    tabla.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    
    // Panel principal con border layout
    JPanel panel = new JPanel(new BorderLayout());
    panel.add(new JScrollPane(tabla), BorderLayout.CENTER);
    
    // Botón de impresión
    JButton btnImprimir = new JButton("Imprimir");
    btnImprimir.addActionListener(e -> {
        try {
            tabla.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(dialog, 
                "Error al imprimir: " + ex.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    });
    
    panel.add(btnImprimir, BorderLayout.SOUTH);
    
    dialog.add(panel);
    dialog.pack();
    dialog.setLocationRelativeTo(null); // Centrar en pantalla
    
    // Asegurarse que esté al frente
    dialog.setAlwaysOnTop(true);
    dialog.setVisible(true);
    dialog.setAlwaysOnTop(false);
}

private int obtenerIdEmpleado(Connection con, String nombreEmpleado) throws SQLException {
    String sql = "SELECT ID FROM empleados WHERE NOMBRE_COMPLETO = ?";
    PreparedStatement stmt = con.prepareStatement(sql);
    stmt.setString(1, nombreEmpleado);
    ResultSet rs = stmt.executeQuery();
    return rs.next() ? rs.getInt("ID") : -1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String periodo = (String) comboPeriodoGeneral.getSelectedItem();
    int meses = obtenerMesesDePeriodo(periodo);
    
    try (Connection con = ConexionBD.obtenerConexion()) {
        // Consultar estadísticas generales
        String sql = "SELECT e.NOMBRE_COMPLETO, " +
                     "SUM(CASE WHEN a.ESTADO = 'Presente' THEN 1 ELSE 0 END) as presentes, " +
                     "SUM(CASE WHEN a.ESTADO = 'Ausente' THEN 1 ELSE 0 END) as ausentes, " +
                     "SUM(CASE WHEN a.ESTADO = 'Tarde' THEN 1 ELSE 0 END) as tardes, " +
                     "COUNT(*) as total " +
                     "FROM asistencias a " +
                     "JOIN empleados e ON a.ID_EMPLEADO = e.ID " +
                     "WHERE a.FECHA BETWEEN DATE('now', ?) AND DATE('now') " +
                     "GROUP BY e.NOMBRE_COMPLETO " +
                     "ORDER BY e.NOMBRE_COMPLETO";
        
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1, "-" + meses + " months");
        
        ResultSet rs = stmt.executeQuery();
        
        // Mostrar resultados en una tabla
        mostrarResultadosEnTabla(rs, "Estadísticas Generales - " + periodo);
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error en la consulta: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEmpleados;
    private javax.swing.JComboBox<String> comboPeriodoGeneral;
    private javax.swing.JComboBox<String> comboPeriodoIndividual;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
