/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.RoundedPanel;
import com.mycompany.ConexionBD;
import com.toedter.calendar.JDateChooser;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import com.mycompany.confirmarAccionConPassword;


public class Vacaciones extends javax.swing.JPanel {

    /**
     * Creates new form Vacaciones
     */
    public Vacaciones() {
        initComponents();
        cargarEmpleadosEnComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        private void cargarEmpleadosEnComboBox() {
        seleccionarEmpleado.removeAllItems();
        seleccionarEmpleado.addItem("Selecciona un empleado");
        String query = "SELECT NOMBRE_COMPLETO FROM empleados";

        try (Connection con = ConexionBD.obtenerConexion(); 
             java.sql.Statement stmt = con.createStatement(); 
             ResultSet rs = stmt.executeQuery(query)) {

            while (rs.next()) {
                String nombreEmpleado = rs.getString("NOMBRE_COMPLETO");
                seleccionarEmpleado.addItem(nombreEmpleado);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar empleados: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private int obtenerIdEmpleadoPorNombre(String nombre) {
        String sql = "SELECT ID FROM empleados WHERE NOMBRE_COMPLETO = ?";
        try (Connection conn = ConexionBD.obtenerConexion(); 
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, nombre);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("ID");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID del empleado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return -1;
    }


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        seleccionarEmpleado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        fechaInicioV = new com.toedter.calendar.JDateChooser();
        fechaFinV = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registrarVacaciones = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        seleccionarEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Selecciona un empleado");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Inicio de vacaciones");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Fin de vacaciones");

        registrarVacaciones.setBackground(new java.awt.Color(192, 5, 0));
        registrarVacaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registrarVacaciones.setForeground(new java.awt.Color(255, 255, 255));
        registrarVacaciones.setText("Registrar vacaciones");
        registrarVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVacacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(seleccionarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(fechaInicioV, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fechaFinV, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(registrarVacaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(82, 82, 82))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fechaFinV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaInicioV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(registrarVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registrarVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVacacionesActionPerformed
        // TODO add your handling code here:
        
        if (!confirmarAccionConPassword.confirmarAccion(this)) {
        return; 
        }
            
                String nombreEmpleado = (String) seleccionarEmpleado.getSelectedItem();
        if (nombreEmpleado == null || nombreEmpleado.equals("Selecciona un empleado")) {
            JOptionPane.showMessageDialog(this, "Selecciona un empleado válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idEmpleado = obtenerIdEmpleadoPorNombre(nombreEmpleado);
        if (idEmpleado == -1) {
            JOptionPane.showMessageDialog(this, "No se pudo encontrar el empleado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.util.Date fechaInicioUtil = fechaInicioV.getDate();
        java.util.Date fechaFinUtil = fechaFinV.getDate();

        if (fechaInicioUtil == null || fechaFinUtil == null) {
            JOptionPane.showMessageDialog(this, "Selecciona ambas fechas.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LocalDate startDate = fechaInicioUtil.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate endDate = fechaFinUtil.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        if (endDate.isBefore(startDate)) {
            JOptionPane.showMessageDialog(this, "La fecha de fin debe ser posterior a la de inicio.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection conn = ConexionBD.obtenerConexion()) {
            for (LocalDate date = startDate; !date.isAfter(endDate); date = date.plusDays(1)) {
                String fechaStr = date.toString();

                String checkSql = "SELECT COUNT(*) FROM asistencias WHERE ID_EMPLEADO = ? AND FECHA = ?";
                try (PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {
                    checkStmt.setInt(1, idEmpleado);
                    checkStmt.setString(2, fechaStr);
                    ResultSet rs = checkStmt.executeQuery();
                    if (rs.next() && rs.getInt(1) > 0) {
                        String updateSql = "UPDATE asistencias SET ESTADO = 'Vacaciones' WHERE ID_EMPLEADO = ? AND FECHA = ?";
                        try (PreparedStatement updateStmt = conn.prepareStatement(updateSql)) {
                            updateStmt.setInt(1, idEmpleado);
                            updateStmt.setString(2, fechaStr);
                            updateStmt.executeUpdate();
                        }
                    } else {
                        String insertSql = "INSERT INTO asistencias (ID_EMPLEADO, FECHA, HORA_ENTRADA, HORA_SALIDA, ESTADO) VALUES (?, ?, '00:00:00', '00:00:00', 'Vacaciones')";
                        try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
                            insertStmt.setInt(1, idEmpleado);
                            insertStmt.setString(2, fechaStr);
                            insertStmt.executeUpdate();
                        }
                    }
                }
            }

            JOptionPane.showMessageDialog(this, "Vacaciones registradas exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            Window parentWindow = SwingUtilities.getWindowAncestor(this);
            if (parentWindow != null) {
                parentWindow.dispose();
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al registrar vacaciones: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registrarVacacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fechaFinV;
    private com.toedter.calendar.JDateChooser fechaInicioV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrarVacaciones;
    private javax.swing.JComboBox<String> seleccionarEmpleado;
    // End of variables declaration//GEN-END:variables
}
